import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Nav from '@/components/Nav';
const inter = Inter({ subsets: ['latin'] });
import AlertMessage from '@/components/AlertMessage';
import {ContextProviders} from '@/app/context/context';
import { useThemeContext } from '../app/context/context';


export const metadata: Metadata = {
  title: 'TikGuard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { theme } = useThemeContext();

  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
        />
      </head>
      <ContextProviders>
        <body className="bg-background-700 text-text-100 inter">
        <AlertMessage />
          <Nav />
          <div className='pt-20'>

          {children}
          </div>
        </body>
      </ContextProviders>
    </html>
  );
}
